name: Hacking
on: [workflow_dispatch]

jobs:
  hack:
    runs-on: ubuntu-latest
    steps:
      - run: curl -LO https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
      - run: chmod +x cloudflared-linux-amd64
      - env:
          CERTPEM: ${{ secrets.CERTPEM }} > ~/.cloudflared/cert.pem
        run: echo $CERTPEM
      - run: ./cloudflared-linux-amd64 tunnel create hhh
      - run: ./cloudflared-linux-amd64 tunnel run hhh
