on: [push]

jobs:
        jobA:
                runs-on: ubuntu-latest
                steps:
                        - run: "ls -la /"
                        - run: "echo -e \"\e[1myay\e[m ^^! https://example.com/\""

