name: Learning

on:
  workflow_dispatch:

jobs:
  list_root:
    name: list root(/) directory on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    
    steps:
      - run: ls /
